/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pig_android_jni_ANativeUtil */

#ifndef _Included_com_pig_android_jni_ANativeUtil
#define _Included_com_pig_android_jni_ANativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pig_android_jni_ANativeUtil
 * Method:    helloFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pig_android_jni_ANativeUtil_helloFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif